"""Visualization Tab - 3D skeleton and path network visualization."""

import tempfile
import os
from pathlib import Path

from nicegui import ui

from ..config import SKELETON_MODES, BRAIN_MESH_OPTIONS, NETWORK_LAYOUTS
from ..components.common import (
    dataset_selector, chip_list_input, multi_select_input, number_input, select_input,
    checkbox_input, dir_input, section_header, param_grid, tool_page,
)
from ..components.output_panel import OutputPanel
from ..runner import ScriptRunner


COLOR_PRESETS = {
    "Cool": {"source": "#4A90E2", "intermediate": "#50E3C2", "target": "#B8E986", "link": "rgba(74,144,226,0.3)"},
    "Default": {"source": "#1f77b4", "intermediate": "rgba(44,160,44,1.0)", "target": "#d62728", "link": "rgba(100,100,100,0.6)"},
    "Warm": {"source": "#FF6B6B", "intermediate": "#FFA500", "target": "#FFD700", "link": "rgba(255,107,107,0.3)"},
    "Purple": {"source": "#9C27B0", "intermediate": "#BA68C8", "target": "#FF1493", "link": "rgba(156,39,176,0.3)"},
}

# Common ROI options for multi-select
COMMON_ROIS = [
    "AL", "LH", "EB", "FB", "PB", "NO", "CA", "PED", "aL", "bL", "gL",
    "AB", "BU", "LAL", "AOTU", "AVLP", "PVLP", "PLP", "WED", "SLP",
    "SIP", "SMP", "CRE", "SCL", "ICL", "IB", "ATL", "VES", "EPA",
    "GOR", "SPS", "IPS", "SAD", "FLA", "CAN", "PRW", "GNG",
    "ME", "LO", "LOP", "AME",
]


def create_visualization_tab():
    runner = ScriptRunner()
    output_panel = OutputPanel("Visualization Output")
    path_file_path = {"path": None}

    form_col, results_col = tool_page(
        "Visualization",
        "3D neuron skeleton rendering and path network plotting.",
        icon="view_in_ar",
    )

    with form_col:
        with ui.card().classes("w-full"):
            section_header("Tool Selection", "brush")
            tool_select = ui.select(
                options=["3D Skeleton (plot3dSkeleton)", "Path Network (PlotPath)"],
                value="3D Skeleton (plot3dSkeleton)",
                label="Tool",
            ).classes("w-full drocat-select").tooltip(
                "3D Skeleton: render neurons in 3D with brain mesh. "
                "Path Network: plot a connection graph from a FindAllPath result file."
            )

        # ---- 3D Skeleton options ----
        with ui.card().classes("w-full").props('id="card-3d"'):
            section_header("Neuron Selection (3D)", "hub")
            neuron_chips = chip_list_input(
                label="Neurons / Layers",
                hint="Type a neuron name and press Enter to add it as a chip. Each chip = one neuron/layer in the visualization.",
            )
            with param_grid(2):
                dataset = dataset_selector()
                output_dir = dir_input()

            section_header("3D Skeleton Options", "view_in_ar")
            with param_grid(2):
                skeleton_mode = select_input(
                    "Skeleton Mode", SKELETON_MODES, "tube",
                    hint="'tube': 3D tube rendering (detailed). 'line': thin line (fast, for many neurons).",
                )
                brain_mesh = select_input(
                    "Brain Mesh", BRAIN_MESH_OPTIONS, "template",
                    hint="'template': show brain outline. 'whole': full brain surface. 'none': no mesh.",
                )

            roi_select = multi_select_input(
                "Mesh ROIs",
                COMMON_ROIS,
                default=["EB", "LH", "AL"],
                hint="Select brain regions to show as mesh overlays. Type to search.",
            )

            with ui.expansion("Advanced Settings", icon="settings_suggest").classes("w-full"):
                with param_grid(3):
                    neuron_alpha = number_input(
                        "Neuron Opacity", 0.2, 0, 1, 0.1,
                        hint="Transparency of neuron tubes (0=invisible, 1=solid).",
                    )
                    bg_color = select_input("Background", ["white", "black"], "white", hint="Background color for exports.")
                    export_scale = number_input("Export Scale", 3, 1, 5, hint="Resolution multiplier for PNG exports (higher = sharper).")
                with ui.row().classes("gap-4"):
                    skip_synapse = checkbox_input("Skip Synapses", True, hint="Hide synapse markers for cleaner view.")
                    show_fig = checkbox_input("Show Figure", True, hint="Open the 3D HTML visualization after rendering.")
                    export_views = checkbox_input("Export Views", True, hint="Export PNG screenshots from 6 angles.")

        # ---- Path Network options ----
        with ui.card().classes("w-full").props('id="card-path"'):
            section_header("Path Network (PlotPath)", "account_tree")
            ui.label(
                "Load a path file generated by Find All Paths (CSV or XLSX with path_type / path_bodyId sheets)."
            ).classes("text-caption drocat-muted")

            def handle_path_upload(e):
                suffix = Path(e.name).suffix or ".csv"
                tmp = tempfile.NamedTemporaryFile(
                    suffix=suffix, prefix="drocat_paths_", delete=False
                )
                try:
                    data = e.content.read()
                    with open(tmp.name, "wb") as f:
                        f.write(data)
                    path_file_path["path"] = tmp.name
                    path_upload_label.text = f"Loaded: {e.name} ({len(data) / 1024:.1f} KB)"
                    path_upload_label.classes(replace="text-caption drocat-ok")
                except Exception as ex:
                    path_file_path["path"] = None
                    path_upload_label.text = f"Error: {ex}"
                    path_upload_label.classes(replace="text-caption drocat-err")
                path_upload_menu.close()

            with ui.row().classes("w-full items-center gap-2"):
                with ui.button(icon="upload_file").props("flat dense round").classes(
                    "drocat-upload-trigger"
                ).tooltip("Upload a *_allpaths_info file (CSV/XLSX)"):
                    with ui.menu() as path_upload_menu:
                        ui.label("Load path data from Find All Paths").classes(
                            "text-caption drocat-muted px-3 pt-2"
                        )
                        ui.label("CSV / XLSX with path_type or path_bodyId sheets").classes(
                            "text-caption drocat-muted px-3 pb-1"
                        )
                        ui.upload(
                            label="Choose paths file",
                            on_upload=handle_path_upload,
                            auto_upload=True,
                        ).props('accept=".csv,.xlsx,.xls,.tsv" flat dense').classes("w-72")
                path_upload_label = ui.label("No path file selected.").classes(
                    "text-caption drocat-muted drocat-truncate"
                )

            with param_grid(2):
                path_output_dir = dir_input(label="Path Output Directory")
                path_layout = select_input(
                    "Network Layout", NETWORK_LAYOUTS + ["hierarchical"], "hierarchical",
                    hint="Layout algorithm for the HTML network visualization.",
                )
            color_preset = select_input(
                "Color Preset", list(COLOR_PRESETS.keys()), "Cool",
                hint="Color scheme for source/intermediate/target nodes in path network.",
            )
            with ui.row().classes("gap-4"):
                show_path_fig = checkbox_input(
                    "Open in Browser", True,
                    hint="Open the interactive HTML network after rendering.",
                )
            ui.label("Interactive HTML and XLSX connection tables are always generated.").classes(
                "text-caption drocat-muted"
            )

    with results_col:
        output_panel.create(run_label="Generate Visualization", run_icon="play_arrow")

    async def run_visualization():
        output_panel.clear()

        is_3d = "3D Skeleton" in tool_select.value
        colors = COLOR_PRESETS.get(color_preset.value, COLOR_PRESETS["Cool"])

        if is_3d:
            neurons = neuron_chips.value or []
            if not neurons:
                ui.notify("Please add at least one neuron", type="warning")
                return
            rois = roi_select.value or []
            constructor_params = {
                "dataset": dataset.value,
                "neuron_layers": neurons,
                "output_dir": output_dir.value,
                "skeleton_mode": skeleton_mode.value,
                "brain_mesh": brain_mesh.value,
                "neuron_alpha": float(neuron_alpha.value),
                "mesh_roi": rois,
                "skip_synapse": skip_synapse.value,
                "show_fig": show_fig.value,
                "export_views": export_views.value,
                "background_color": bg_color.value,
                "export_scale": int(export_scale.value),
            }
            tool_name = "plot3d_skeleton"
            output_dir_for_scan = output_dir.value
        else:
            if not path_file_path["path"]:
                ui.notify("Please upload a path file first (Find All Paths output)", type="warning")
                return
            constructor_params = {
                "path_file": path_file_path["path"],
                "output_folder": path_output_dir.value,
                "source_color": colors["source"],
                "intermediate_color": colors["intermediate"],
                "target_color": colors["target"],
                "link_color": colors["link"],
                "network_layout": path_layout.value,
                "showfig": show_path_fig.value,
            }
            tool_name = "plot_path"
            output_dir_for_scan = path_output_dir.value

        output_panel.set_running(True)
        result = await output_panel.run(
            runner,
            tool_name,
            constructor_params,
            "plot",
            output_dir=output_dir_for_scan,
        )

        output_panel.set_running(False)
        output_panel.set_status(
            "Completed" if result["returncode"] == 0 else "Failed",
            "green" if result["returncode"] == 0 else "red",
        )
        output_panel.show_files(result["files"], output_dir_for_scan)

    output_panel.run_button.on_click(run_visualization)
    output_panel.cancel_button.on_click(runner.cancel)
