import gzip
import shutil
import pandas as pd
from pathlib import Path

def extract_gz(file_path, output_path):
    """Extract a .gz file."""
    with gzip.open(file_path, 'rb') as f_in:
        with open(output_path, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

def prepare_fafb_data(data_dir):
    """
    Prepare FAFB data for analysis.
    
    Args:
        data_dir (str): Path to the FAFB dataset directory (e.g., 'datasets/flywire_FAFB_v783')
        
    Returns:
        str: Path to the prepared neuron DataFrame CSV.
        str: Path to the connection CSV.
    """
    data_path = Path(data_dir)
    downloads_dir = data_path / 'downloads'
    
    if not downloads_dir.exists():
        downloads_dir.mkdir(exist_ok=True)
        
    # Define required files
    conn_file_gz = downloads_dir / 'connections_princeton_no_threshold.csv.gz'
    types_file_gz = downloads_dir / 'consolidated_cell_types.csv.gz'
    
    # Use merged files if available (generated by FAFB_file_converter or BANC_file_converter)
    dataset_name = data_path.name
    merged_conn_file = data_path / f'{dataset_name}_merged_connections.csv'
    merged_neuron_file = data_path / f'{dataset_name}_allneurons_neuron_df.csv'
    
    if merged_conn_file.exists() and merged_neuron_file.exists():
        return str(merged_neuron_file), str(merged_conn_file)

    # Fallback to legacy names or uncompressed files in downloads
    conn_file = downloads_dir / 'connections_princeton_no_threshold.csv'
    types_file = downloads_dir / 'consolidated_cell_types.csv'
    
    output_neuron_df = data_path / 'flywire_v783_allneurons_neuron_df.csv'
    
    # Check if raw files exist
    # If output files already exist, we don't strictly need the .gz files
    if output_neuron_df.exists() and conn_file.exists():
        return str(output_neuron_df), str(conn_file)

    if not conn_file_gz.exists() or not types_file_gz.exists():
        # Check if uncompressed files exist (maybe user extracted them manually)
        if conn_file.exists() and types_file.exists():
             pass # Proceed to generate neuron df if needed
        else:
            # Generic error message for missing files
            raise FileNotFoundError(
                f"Required data files not found in {data_dir}.\n"
                f"Please ensure the following files exist in {downloads_dir}:\n"
                "1. connections_princeton_no_threshold.csv.gz (or connections_princeton.csv.gz)\n"
                "2. consolidated_cell_types.csv.gz (or neurons.csv.gz)\n"
                "3. sk_lod1_783_healed.zip (optional, for visualization)\n"
                "If using BANC, ensure BANC_file_converter has run successfully."
            )
        
    # Extract if needed
    if not conn_file.exists():
        print(f"Extracting {conn_file_gz}...")
        extract_gz(conn_file_gz, conn_file)
        
    if not types_file.exists():
        print(f"Extracting {types_file_gz}...")
        extract_gz(types_file_gz, types_file)
        
    # Create unified neuron DataFrame if needed
    if not output_neuron_df.exists():
        print("Generating unified neuron DataFrame...")
        
        # Read connections to calculate synapse counts
        print("  Reading connections...")
        # Use string for IDs to handle large integers
        df_conn = pd.read_csv(conn_file, dtype={'pre_root_id': str, 'post_root_id': str})
        
        # Calculate pre counts (outgoing)
        print("  Calculating pre counts...")
        pre_counts = df_conn.groupby('pre_root_id')['syn_count'].sum().reset_index()
        pre_counts.columns = ['bodyId', 'pre']
        
        # Calculate post counts (incoming)
        print("  Calculating post counts...")
        post_counts = df_conn.groupby('post_root_id')['syn_count'].sum().reset_index()
        post_counts.columns = ['bodyId', 'post']
        
        # Read types
        print("  Reading cell types...")
        df_types = pd.read_csv(types_file, dtype={'root_id': str})
        df_types = df_types.rename(columns={'root_id': 'bodyId', 'primary_type': 'type'})
        
        # Merge everything
        print("  Merging data...")
        # Start with all unique bodyIds from types
        df_neuron = df_types[['bodyId', 'type']].copy()
        
        # Merge counts
        df_neuron = df_neuron.merge(pre_counts, on='bodyId', how='left')
        df_neuron = df_neuron.merge(post_counts, on='bodyId', how='left')
        
        # Fill NaNs with 0
        df_neuron['pre'] = df_neuron['pre'].fillna(0).astype(int)
        df_neuron['post'] = df_neuron['post'].fillna(0).astype(int)
        
        # Save
        print(f"  Saving to {output_neuron_df}...")
        df_neuron.to_csv(output_neuron_df, index=False)
        print("Done.")
        
    return str(output_neuron_df), str(conn_file)

def get_fafb_skeleton_zip(data_dir):
    """Get path to skeleton zip file."""
    data_path = Path(data_dir)
    
    # 1. Check for standardized name (from FAFB_file_converter)
    # Try to guess dataset name from dir name or standard
    dataset_name = data_path.name
    std_zip = data_path / f"{dataset_name}_skeletons.zip"
    if std_zip.exists():
        return str(std_zip)
        
    # 2. Check for original name in root
    zip_path = data_path / 'sk_lod1_783_healed.zip'
    if zip_path.exists():
        return str(zip_path)
        
    # 3. Check in downloads
    downloads_zip = data_path / 'downloads' / 'sk_lod1_783_healed.zip'
    if downloads_zip.exists():
        return str(downloads_zip)
        
    print(f"Warning: Skeleton zip not found in {data_dir} or downloads")
    return None

def get_fafb_skeleton_parquet(data_dir):
    """Get path to skeleton parquet file."""
    data_path = Path(data_dir)
    dataset_name = data_path.name
    std_pq = data_path / f"{dataset_name}_skeletons.parquet"
    if std_pq.exists():
        return str(std_pq)
    return None
