import gzip
import shutil
import pandas as pd
from pathlib import Path

try:
    from .flywire_ids import (
        is_banc_dataset,
        normalize_flywire_id_columns,
    )
except ImportError:
    from flywire_ids import is_banc_dataset, normalize_flywire_id_columns

def extract_gz(file_path, output_path):
    """Extract a .gz file."""
    with gzip.open(file_path, 'rb') as f_in:
        with open(output_path, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

def prepare_flywire_data(data_dir):
    """
    Prepare local FlyWire data for analysis.
    
    Args:
        data_dir (str): Path to a FAFB or BANC dataset directory.
        
    Returns:
        str: Path to the prepared neuron DataFrame CSV.
        str: Path to the connection CSV.
    """
    data_path = Path(data_dir)
    downloads_dir = data_path / 'downloads'
    
    if not downloads_dir.exists():
        downloads_dir.mkdir(exist_ok=True)
        
    # Define required files
    conn_file_gz = downloads_dir / 'connections_princeton_no_threshold.csv.gz'
    types_file_gz = downloads_dir / 'consolidated_cell_types.csv.gz'
    
    # Use merged files if available (generated by either converter). The
    # parquet is canonical, while older CSV output remains readable.
    dataset_name = data_path.name
    merged_conn_candidates = [
        data_path / f'{dataset_name}_merged_connections.parquet',
        data_path / f'{dataset_name}_merged_connections.csv',
    ]
    merged_neuron_candidates = [
        data_path / f'{dataset_name}_allneurons_neuron_df.parquet',
        data_path / f'{dataset_name}_allneurons_neuron_df.csv',
    ]
    merged_conn_file = next(
        (path for path in merged_conn_candidates if path.exists()), None
    )
    merged_neuron_file = next(
        (path for path in merged_neuron_candidates if path.exists()), None
    )

    if merged_conn_file is not None and merged_neuron_file is not None:
        return str(merged_neuron_file), str(merged_conn_file)

    # BANC has a different source schema and must never fall through to the
    # FAFB raw-file names below.  Its converter owns preparation of missing
    # local tables; this helper only resolves already-prepared outputs.
    if is_banc_dataset(dataset_name):
        raise FileNotFoundError(
            f"Prepared BANC tables are missing from {data_dir}. "
            "Run BANC_file_converter.ensure_banc_data first."
        )

    # Fallback to legacy names or uncompressed files in downloads
    conn_file = downloads_dir / 'connections_princeton_no_threshold.csv'
    types_file = downloads_dir / 'consolidated_cell_types.csv'
    
    output_neuron_df = data_path / 'flywire_v783_allneurons_neuron_df.csv'
    
    # Check if raw files exist
    # If output files already exist, we don't strictly need the .gz files
    if output_neuron_df.exists() and conn_file.exists():
        return str(output_neuron_df), str(conn_file)

    if not conn_file_gz.exists() or not types_file_gz.exists():
        # Check if uncompressed files exist (maybe user extracted them manually)
        if conn_file.exists() and types_file.exists():
             pass # Proceed to generate neuron df if needed
        else:
            # Generic error message for missing files (one-time download +
            # conversion; same story the converters print)
            dataset_key = 'banc' if is_banc_dataset(dataset_name) else 'fafb'
            converter = 'BANC_file_converter' if dataset_key == 'banc' else 'FAFB_file_converter'
            raise FileNotFoundError(
                f"Required data files not found in {data_dir}.\n"
                f"This is a one-time preparation step: download the files from\n"
                f"https://codex.flywire.ai/api/download?dataset={dataset_key}\n"
                f"save them into {downloads_dir}, then run the one-time conversion:\n"
                f"python src/{converter}.py\n"
                f"Required files in {downloads_dir}:\n"
                "1. connections_princeton_no_threshold.csv.gz (or connections_princeton.csv.gz)\n"
                "2. consolidated_cell_types.csv.gz (or neurons.csv.gz)\n"
                "3. sk_lod1_783_healed.zip (optional, for visualization)\n"
            )
        
    # Extract if needed
    if not conn_file.exists():
        print(f"Extracting {conn_file_gz}...")
        extract_gz(conn_file_gz, conn_file)
        
    if not types_file.exists():
        print(f"Extracting {types_file_gz}...")
        extract_gz(types_file_gz, types_file)
        
    # Create unified neuron DataFrame if needed
    if not output_neuron_df.exists():
        print("Generating unified neuron DataFrame...")
        
        # Read connections to calculate synapse counts
        print("  Reading connections...")
        # Use string for IDs to handle large integers
        df_conn = pd.read_csv(conn_file, dtype={'pre_root_id': str, 'post_root_id': str})
        
        # Calculate pre counts (outgoing)
        print("  Calculating pre counts...")
        pre_counts = df_conn.groupby('pre_root_id')['syn_count'].sum().reset_index()
        pre_counts.columns = ['bodyId', 'pre']
        
        # Calculate post counts (incoming)
        print("  Calculating post counts...")
        post_counts = df_conn.groupby('post_root_id')['syn_count'].sum().reset_index()
        post_counts.columns = ['bodyId', 'post']
        
        # Read types
        print("  Reading cell types...")
        df_types = pd.read_csv(types_file, dtype={'root_id': str})
        df_types = df_types.rename(columns={'root_id': 'bodyId', 'primary_type': 'type'})
        
        # Merge everything
        print("  Merging data...")
        # Start with all unique bodyIds from types
        df_neuron = df_types[['bodyId', 'type']].copy()
        normalize_flywire_id_columns(df_neuron, ['bodyId'])
        
        # Merge counts
        df_neuron = df_neuron.merge(pre_counts, on='bodyId', how='left')
        df_neuron = df_neuron.merge(post_counts, on='bodyId', how='left')
        
        # Fill NaNs with 0
        df_neuron['pre'] = df_neuron['pre'].fillna(0).astype(int)
        df_neuron['post'] = df_neuron['post'].fillna(0).astype(int)
        
        # Save
        print(f"  Saving to {output_neuron_df}...")
        df_neuron.to_csv(output_neuron_df, index=False)
        print("Done.")
        
    return str(output_neuron_df), str(conn_file)


def prepare_fafb_data(data_dir):
    """Backward-compatible alias for :func:`prepare_flywire_data`."""

    return prepare_flywire_data(data_dir)

def get_fafb_skeleton_zip(data_dir):
    """Get path to skeleton zip file."""
    data_path = Path(data_dir)

    if is_banc_dataset(data_path.name):
        return None
    
    # 1. Check for standardized name (from FAFB_file_converter)
    # Try to guess dataset name from dir name or standard
    dataset_name = data_path.name
    std_zip = data_path / f"{dataset_name}_skeletons.zip"
    if std_zip.exists():
        return str(std_zip)
        
    # 2. Check for original name in root
    zip_path = data_path / 'sk_lod1_783_healed.zip'
    if zip_path.exists():
        return str(zip_path)
        
    # 3. Check in downloads
    downloads_zip = data_path / 'downloads' / 'sk_lod1_783_healed.zip'
    if downloads_zip.exists():
        return str(downloads_zip)
        
    print(f"Warning: Skeleton zip not found in {data_dir} or downloads")
    return None


def get_fafb_skeleton_bundle(data_dir):
    """Get a healed-bundle reader for the FAFB skeleton source.

    Resolves ``sk_lod1_783_healed.zst`` first, then falls back to the legacy
    healed ZIP.  The returned :class:`fafb_bundle.FAFBSkeletonBundle`
    performs lazy per-skeleton conversion on the ZIP fallback path (each
    loaded skeleton is converted into the .zst container and its ZIP entry
    is removed logically; physical removal happens by batched compaction).
    Returns None when neither file exists.
    """
    data_path = Path(data_dir)
    if is_banc_dataset(data_path.name):
        return None
    try:
        from fafb_bundle import open_bundle
        return open_bundle(data_path, lazy_convert=True)
    except Exception:
        return None

def get_fafb_skeleton_parquet(data_dir):
    """Get path to skeleton parquet file."""
    data_path = Path(data_dir)
    dataset_name = data_path.name
    std_pq = data_path / f"{dataset_name}_skeletons.parquet"
    if std_pq.exists():
        return str(std_pq)
    return None


# =============================================================================
# FAFB skeleton quality pipeline (shared with the visualization pipeline)
# =============================================================================
# The visualization pipeline checks FAFB skeletons in this order:
#   1. local first  - extrusion-fixed skeletons cached under
#                     ``cache/{dataset}/API_cache/skeletons/``, then the
#                     healed skeleton bundle (``{bodyId}.swc``),
#   2. extrusion test - edge-length analysis on the local skeletons, with
#                     per-neuron results cached in
#                     ``cache/{dataset}/extrusion_check_results.parquet``,
#   3. online fallback - extrusion-affected or missing neurons are fetched
#                     through the CAVE API (token-gated),
#   4. local repair   - if CAVE cannot repair an affected tree, remove only a
#                     safely identified extrusion subtree in memory.
# These helpers expose that pipeline so every consumer (e.g. NBLAST
# dotprops building) follows the same behavior.

EXTRUSION_CHECK_FILENAME = "extrusion_check_results.parquet"

# ``has_extrusion`` is the detection result and must never be overwritten by
# the outcome of a repair attempt.  The status column is deliberately kept in
# the same parquet so an old boolean-only cache remains readable and a failed
# CAVE repair can be retried on the next run without re-running detection.
EXTRUSION_REPAIR_PENDING = "pending"
EXTRUSION_REPAIR_API_REPAIRED = "api_repaired"
EXTRUSION_REPAIR_LOCAL_FALLBACK = "local_fallback"
EXTRUSION_REPAIR_API_FAILED = "api_failed"
EXTRUSION_REPAIR_CLEAN = "clean"


def extrusion_check_cache_path(project_root, dataset_folder):
    """Path of the cached extrusion check results for a dataset folder."""
    return Path(project_root) / "cache" / dataset_folder / EXTRUSION_CHECK_FILENAME


def load_extrusion_check_cache(project_root, dataset_folder):
    """Cached extrusion results: {bodyId(str): has_extrusion(bool)}."""
    path = extrusion_check_cache_path(project_root, dataset_folder)
    if not path.exists():
        return {}
    try:
        import pandas as pd

        df = pd.read_parquet(path)
        return dict(zip(df["bodyId"].astype(str), df["has_extrusion"]))
    except Exception:
        return {}


def load_extrusion_repair_status(project_root, dataset_folder):
    """Load repair outcomes keyed by string body ID.

    Older cache files do not have a ``repair_status`` column.  Their flagged
    rows are treated as ``pending`` so they continue through the CAVE/local
    repair path, while clean rows are treated as ``clean``.
    """
    path = extrusion_check_cache_path(project_root, dataset_folder)
    if not path.exists():
        return {}
    try:
        df = pd.read_parquet(path)
        if "bodyId" not in df.columns or "has_extrusion" not in df.columns:
            return {}
        statuses = {}
        has_status = "repair_status" in df.columns
        for _, row in df.iterrows():
            body_id = str(row["bodyId"])
            default = (
                EXTRUSION_REPAIR_PENDING
                if bool(row["has_extrusion"])
                else EXTRUSION_REPAIR_CLEAN
            )
            value = row["repair_status"] if has_status else default
            if pd.isna(value) or not str(value).strip():
                value = default
            statuses[body_id] = str(value)
        return statuses
    except Exception:
        return {}


def _write_extrusion_cache(project_root, dataset_folder, results, statuses):
    """Write the complete merged extrusion cache (best effort)."""
    if not results:
        return
    try:
        path = extrusion_check_cache_path(project_root, dataset_folder)
        path.parent.mkdir(parents=True, exist_ok=True)
        rows = [
            {
                "bodyId": str(body_id),
                "has_extrusion": bool(results[body_id]),
                "repair_status": str(
                    statuses.get(
                        body_id,
                        EXTRUSION_REPAIR_PENDING
                        if bool(results[body_id])
                        else EXTRUSION_REPAIR_CLEAN,
                    )
                ),
            }
            for body_id in sorted(results, key=str)
        ]
        pd.DataFrame(rows).to_parquet(path, index=False)
    except Exception:
        pass


def save_extrusion_check_cache(project_root, dataset_folder, results):
    """Merge and persist extrusion check results (best-effort).

    A run may inspect only a subset of a large healed bundle.  Merge-on-write
    preserves prior rows and their repair status instead of making the cache
    forget neurons checked in earlier runs.
    """
    if not results:
        return
    existing = load_extrusion_check_cache(project_root, dataset_folder)
    statuses = load_extrusion_repair_status(project_root, dataset_folder)
    for body_id, value in results.items():
        key = str(body_id)
        if isinstance(value, dict):
            has_extrusion = bool(value.get("has_extrusion", False))
            requested_status = value.get("repair_status")
        else:
            has_extrusion = bool(value)
            requested_status = None
        existing[key] = has_extrusion
        if requested_status is not None:
            statuses[key] = str(requested_status)
        elif not has_extrusion:
            statuses[key] = EXTRUSION_REPAIR_CLEAN
        else:
            # A newly detected flag has not yet been repaired.  Do not reset
            # a status belonging to an already-cached row unless this result
            # is genuinely new.
            statuses.setdefault(key, EXTRUSION_REPAIR_PENDING)
    _write_extrusion_cache(project_root, dataset_folder, existing, statuses)


def set_extrusion_repair_status(project_root, dataset_folder, statuses):
    """Persist repair outcomes without changing cached detection results.

    ``statuses`` maps body IDs to one of the ``EXTRUSION_REPAIR_*`` values.
    Missing detection rows are conservatively created as flagged rows, which
    keeps a repair failure retryable rather than silently making it clean.
    """
    if not statuses:
        return
    results = load_extrusion_check_cache(project_root, dataset_folder)
    current_statuses = load_extrusion_repair_status(
        project_root, dataset_folder)
    for body_id, status in statuses.items():
        key = str(body_id)
        results.setdefault(key, True)
        current_statuses[key] = str(status)
    _write_extrusion_cache(
        project_root, dataset_folder, results, current_statuses)


def diagnose_extrusion_nodes(neuron, ratio_threshold=10.0,
                             absolute_threshold=50000.0):
    """Locate skeleton edges that are plausible extrusion branches.

    The normal extrusion check is mesh-based.  When its CAVE replacement is
    unavailable, this node-level diagnosis gives the caller a conservative
    local repair option by mapping the same long-edge signal back to the
    source tree.  A uniformly large skeleton is not treated as locally
    repairable: there must be a relative outlier, or an absolute spike that
    is also at least three times the median edge length.

    Returns a dictionary containing the candidate child node IDs and edge
    statistics.  The function never mutates ``neuron``.
    """
    import numpy as np

    nodes = getattr(neuron, "nodes", None)
    required = {"node_id", "parent_id", "x", "y", "z"}
    if nodes is None or not required.issubset(nodes.columns):
        return {
            "detected": False,
            "candidate_child_ids": [],
            "candidate_parent_ids": [],
            "candidate_edge_lengths": [],
            "median_edge_length": 0.0,
            "max_edge_length": 0.0,
            "edge_ratio": 0.0,
        }

    frame = nodes[["node_id", "parent_id", "x", "y", "z"]].copy()
    coordinates = frame[["x", "y", "z"]].apply(
        pd.to_numeric, errors="coerce"
    ).to_numpy(dtype=float)
    node_ids = frame["node_id"].tolist()
    node_set = set(node_ids)
    row_by_id = {node_id: index for index, node_id in enumerate(node_ids)}

    child_ids = []
    parent_ids = []
    edge_lengths = []
    for index, parent_id in enumerate(frame["parent_id"].tolist()):
        child_id = node_ids[index]
        if pd.isna(parent_id) or parent_id not in node_set:
            continue
        parent_index = row_by_id[parent_id]
        if not (np.isfinite(coordinates[index]).all()
                and np.isfinite(coordinates[parent_index]).all()):
            continue
        length = float(np.linalg.norm(
            coordinates[index] - coordinates[parent_index]
        ))
        if length <= 0:
            continue
        child_ids.append(child_id)
        parent_ids.append(parent_id)
        edge_lengths.append(length)

    if not edge_lengths:
        return {
            "detected": False,
            "candidate_child_ids": [],
            "candidate_parent_ids": [],
            "candidate_edge_lengths": [],
            "median_edge_length": 0.0,
            "max_edge_length": 0.0,
            "edge_ratio": 0.0,
        }

    lengths = np.asarray(edge_lengths, dtype=float)
    median_edge = float(np.median(lengths))
    max_edge = float(np.max(lengths))
    edge_ratio = max_edge / median_edge if median_edge > 0 else 0.0
    detected = bool(
        edge_ratio > float(ratio_threshold)
        or max_edge > float(absolute_threshold)
    )
    if not detected:
        candidate_mask = np.zeros(len(lengths), dtype=bool)
    else:
        relative_mask = (
            lengths > float(ratio_threshold) * median_edge
            if median_edge > 0
            else lengths == max_edge
        )
        # The mesh detector also has an absolute 50 µm guard.  Require a
        # meaningful local contrast before using that guard to prune nodes;
        # otherwise a normal skeleton whose whole edge scale is large could
        # lose an arbitrary terminal half.
        absolute_mask = (
            (lengths > float(absolute_threshold))
            & (lengths > 3.0 * median_edge)
            if median_edge > 0
            else lengths > float(absolute_threshold)
        )
        candidate_mask = relative_mask | absolute_mask

    candidate_indices = np.flatnonzero(candidate_mask)
    return {
        "detected": detected,
        "candidate_child_ids": [child_ids[index] for index in candidate_indices],
        "candidate_parent_ids": [parent_ids[index] for index in candidate_indices],
        "candidate_edge_lengths": [float(lengths[index]) for index in candidate_indices],
        "median_edge_length": median_edge,
        "max_edge_length": max_edge,
        "edge_ratio": edge_ratio,
    }


def repair_extruded_skeleton(neuron, max_removed_fraction=0.50,
                             min_remaining_nodes=2):
    """Drop only safely localized extrusion subtrees from a TreeNeuron.

    This is an in-memory fallback for a failed CAVE repair.  Candidate edges
    come from :func:`diagnose_extrusion_nodes`; each candidate removes the
    child and its descendants, never the parent side of the edge.  A repair
    is skipped when it would remove more than ``max_removed_fraction`` of the
    tree or leave fewer than ``min_remaining_nodes`` nodes.

    Returns
    -------
    tuple
        ``(neuron_or_repaired_copy, stats)``.  The first item is the original
        object when no safe repair is possible.  Derived repairs are never
        written to the raw skeleton cache.
    """
    import navis

    diagnosis = diagnose_extrusion_nodes(neuron)
    nodes = getattr(neuron, "nodes", None)
    raw_count = len(nodes) if nodes is not None else 0
    stats = {
        **diagnosis,
        "repaired": False,
        "raw_nodes": raw_count,
        "remaining_nodes": raw_count,
        "removed_nodes": 0,
        "removed_node_ids": [],
    }
    if (raw_count < int(min_remaining_nodes)
            or not diagnosis["candidate_child_ids"]):
        return neuron, stats

    parent_map = {}
    node_ids = set(nodes["node_id"].tolist())
    for child_id, parent_id in zip(
            nodes["node_id"].tolist(), nodes["parent_id"].tolist()):
        if pd.isna(parent_id) or parent_id not in node_ids:
            continue
        parent_map[child_id] = parent_id

    children = {}
    for child_id, parent_id in parent_map.items():
        children.setdefault(parent_id, []).append(child_id)

    def subtree(root_id):
        found = set()
        pending = [root_id]
        while pending:
            current = pending.pop()
            if current in found:
                continue
            found.add(current)
            pending.extend(children.get(current, ()))
        return found

    candidate_rows = sorted(
        zip(
            diagnosis["candidate_edge_lengths"],
            diagnosis["candidate_child_ids"],
        ),
        key=lambda row: row[0],
        reverse=True,
    )
    removed = set()
    accepted = []
    max_removed = max(1, int(raw_count * float(max_removed_fraction)))
    for edge_length, child_id in candidate_rows:
        if child_id in removed or child_id not in parent_map:
            continue
        branch = subtree(child_id)
        proposed = removed | branch
        if len(proposed) > max_removed:
            continue
        if raw_count - len(proposed) < int(min_remaining_nodes):
            continue
        removed = proposed
        accepted.append((child_id, float(edge_length)))

    if not removed:
        return neuron, stats

    ordered_removed = sorted(
        removed, key=lambda node_id: (type(node_id).__name__, str(node_id))
    )
    try:
        repaired = navis.remove_nodes(
            neuron, ordered_removed, inplace=False
        )
    except Exception:
        return neuron, stats
    if repaired is None or len(getattr(repaired, "nodes", ())) < int(min_remaining_nodes):
        return neuron, stats

    stats.update({
        "repaired": True,
        "remaining_nodes": len(repaired.nodes),
        "removed_nodes": len(removed),
        "removed_node_ids": ordered_removed,
        "accepted_edges": [
            {"child_id": child_id, "edge_length": edge_length}
            for child_id, edge_length in accepted
        ],
    })
    return repaired, stats


def detect_extrusion(neuron, simplification=0.95, tube_points=6):
    """Whether a skeleton carries extrusion artifacts (edge-length analysis).

    Mirrors ``VisualizeSkeleton._detect_extrusions_in_skeletons``: convert
    the skeleton to a simplified tube mesh and flag neurons whose edge
    lengths spike (ratio > 10 or a single edge > 50,000 nm).

    The analysis is vectorized over the mesh's unique edges (``trimesh``
    edge index) instead of a Python loop over faces — identical statistics,
    ~20x faster; the open3d quadric decimation (the dominant phase) is
    skipped when the tube mesh is already at or below the target face count.
    """
    import numpy as np
    import navis

    try:
        if hasattr(neuron, "nodes") and "radius" in neuron.nodes.columns:
            invalid = (neuron.nodes["radius"] <= 0) | neuron.nodes["radius"].isna()
            if invalid.any():
                neuron.nodes.loc[invalid, "radius"] = 1
        elif hasattr(neuron, "nodes"):
            neuron.nodes["radius"] = 1

        mesh_neuron = navis.conversion.tree2meshneuron(
            neuron, tube_points=tube_points, use_normals=True
        )
        if not hasattr(mesh_neuron, "trimesh"):
            return False

        n_faces = len(mesh_neuron.trimesh.faces)
        target_faces = max(100, int(n_faces * (1 - simplification)))
        if n_faces > target_faces:
            # Use the same accelerated fine-quality decimator as FAFB
            # visualization/cache preparation.  It prefilters very large
            # tube meshes with one cheap clustering pass, then uses QEM for
            # the final target.  Small meshes fall back to direct QEM.
            try:
                from flywire_mesh_cache import simplify_mesh_fine
            except ImportError:
                from .flywire_mesh_cache import simplify_mesh_fine
            mesh = simplify_mesh_fine(mesh_neuron.trimesh, target_faces)
        else:
            # Already small enough: analyzing the tube mesh directly avoids
            # the (dominant) decimation cost without changing the result.
            mesh = mesh_neuron.trimesh

        edge_ends = mesh.vertices[mesh.edges_unique]
        edge_lengths = np.linalg.norm(
            edge_ends[:, 0, :] - edge_ends[:, 1, :], axis=1
        )
        if len(edge_lengths) == 0:
            return False

        median_edge = np.median(edge_lengths)
        max_edge = np.max(edge_lengths)
        edge_ratio = max_edge / median_edge if median_edge > 0 else 0
        return bool(edge_ratio > 10 or max_edge > 50000)
    except Exception:
        return False


def _extrusion_worker(task, simplification=0.95):
    """Module-level worker for the parallel extrusion check (picklable)."""
    body_id, neuron = task
    return body_id, bool(detect_extrusion(neuron, simplification=simplification))


def flag_extrusions(project_root, dataset_folder, skeletons, verbose=False,
                    log=None, simplification=0.95, n_workers=0,
                    use_cache=True):
    """Extrusion check with cached results; returns flagged body ids (int).

    ``skeletons`` maps bodyId -> TreeNeuron. Previously checked neurons are
    served from ``extrusion_check_results.parquet``; new results are
    persisted so the analysis runs once per neuron.

    ``use_cache=False`` runs the check fully in memory: the parquet cache
    is neither read nor written, so callers with caching disabled leave
    ``extrusion_check_results.parquet`` untouched.

    Unchecked neurons are analyzed in a parallel batch (process pool,
    ``n_workers``; 0 = auto up to 8). Platforms/sandboxes where the pool
    cannot start (e.g. no POSIX semaphores) fall back to a serial pass, so
    the check always completes.
    """
    import functools
    import os
    import sys
    from concurrent.futures import ProcessPoolExecutor

    from tqdm import tqdm

    # Skeleton loaders may preserve body IDs as strings (the FAFB neuron
    # tables intentionally use strings to avoid precision loss), while this
    # routine normalizes IDs to ``int`` before looking them up. Normalize the
    # mapping once at the boundary so ``skeletons[body_id]`` remains valid for
    # both ZIP-loaded and API-cached skeletons.
    normalized_skeletons = {
        int(body_id): neuron
        for body_id, neuron in skeletons.items()
    }
    skeletons = normalized_skeletons

    cache = (load_extrusion_check_cache(project_root, dataset_folder)
             if use_cache else {})
    flagged = [int(b) for b in skeletons if cache.get(str(b), False)]
    to_check = [int(b) for b in skeletons if str(b) not in cache]
    if not to_check:
        if flagged and (log or verbose):
            (log or print)(
                f"Extrusion check: {len(flagged)} known issue(s) from cache."
            )
        return flagged

    def _report(msg):
        if log is not None:
            log(msg)
        elif verbose:
            print(msg)

    new_results = {}
    pbar = tqdm(total=len(to_check), desc="Checking extrusions", unit="neuron",
                disable=not verbose, leave=False, file=sys.stdout)
    worker = functools.partial(_extrusion_worker, simplification=simplification)

    workers = int(n_workers) if int(n_workers) > 0 else min(
        8, len(to_check), os.cpu_count() or 1)
    if workers > 1:
        try:
            import multiprocessing as mp

            # fork inherits the parent's navis/open3d imports (no per-worker
            # startup cost) and is available on macOS/Linux; the serial pass
            # below covers environments where the pool cannot start.
            ctx = (mp.get_context("fork")
                   if hasattr(mp, "get_context")
                   and "fork" in mp.get_all_start_methods()
                   else mp.get_context("spawn"))
            with ProcessPoolExecutor(max_workers=workers, mp_context=ctx) as ex:
                for body_id, has_extrusion in ex.map(
                        worker,
                        [(bid, skeletons[bid]) for bid in to_check],
                        chunksize=max(1, len(to_check) // (workers * 4))):
                    new_results[str(body_id)] = has_extrusion
                    if has_extrusion:
                        flagged.append(body_id)
                    pbar.update(1)
                    pbar.set_postfix_str(f"{body_id}")
        except Exception:
            # The pool could not start (or died mid-run): redo the batch
            # serially so the check always completes.
            new_results = {}
            flagged = [int(b) for b in skeletons if cache.get(str(b), False)]
            pbar.n = 0
            pbar.refresh()
            for bid in to_check:
                has_extrusion = detect_extrusion(
                    skeletons[bid], simplification=simplification
                )
                new_results[str(bid)] = has_extrusion
                if has_extrusion:
                    flagged.append(bid)
                pbar.update(1)
                pbar.set_postfix_str(f"{bid}")
    else:
        for bid in to_check:
            has_extrusion = detect_extrusion(
                skeletons[bid], simplification=simplification
            )
            new_results[str(bid)] = has_extrusion
            if has_extrusion:
                flagged.append(bid)
            pbar.update(1)
            pbar.set_postfix_str(f"{bid}")

    pbar.close()
    if use_cache:
        save_extrusion_check_cache(project_root, dataset_folder, new_results)
    if flagged:
        _report(f"Extrusion check: {len(flagged)} neuron(s) flagged for "
                "API replacement.")
    return flagged
