import gzip
import shutil
import pandas as pd
from pathlib import Path

try:
    from .flywire_ids import (
        is_banc_dataset,
        normalize_flywire_id_columns,
    )
except ImportError:
    from flywire_ids import is_banc_dataset, normalize_flywire_id_columns

def extract_gz(file_path, output_path):
    """Extract a .gz file."""
    with gzip.open(file_path, 'rb') as f_in:
        with open(output_path, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

def prepare_flywire_data(data_dir):
    """
    Prepare local FlyWire data for analysis.
    
    Args:
        data_dir (str): Path to a FAFB or BANC dataset directory.
        
    Returns:
        str: Path to the prepared neuron DataFrame CSV.
        str: Path to the connection CSV.
    """
    data_path = Path(data_dir)
    downloads_dir = data_path / 'downloads'
    
    if not downloads_dir.exists():
        downloads_dir.mkdir(exist_ok=True)
        
    # Define required files
    conn_file_gz = downloads_dir / 'connections_princeton_no_threshold.csv.gz'
    types_file_gz = downloads_dir / 'consolidated_cell_types.csv.gz'
    
    # Use merged files if available (generated by either converter). The
    # parquet is canonical, while older CSV output remains readable.
    dataset_name = data_path.name
    merged_conn_candidates = [
        data_path / f'{dataset_name}_merged_connections.parquet',
        data_path / f'{dataset_name}_merged_connections.csv',
    ]
    merged_neuron_candidates = [
        data_path / f'{dataset_name}_allneurons_neuron_df.parquet',
        data_path / f'{dataset_name}_allneurons_neuron_df.csv',
    ]
    merged_conn_file = next(
        (path for path in merged_conn_candidates if path.exists()), None
    )
    merged_neuron_file = next(
        (path for path in merged_neuron_candidates if path.exists()), None
    )

    if merged_conn_file is not None and merged_neuron_file is not None:
        return str(merged_neuron_file), str(merged_conn_file)

    # BANC has a different source schema and must never fall through to the
    # FAFB raw-file names below.  Its converter owns preparation of missing
    # local tables; this helper only resolves already-prepared outputs.
    if is_banc_dataset(dataset_name):
        raise FileNotFoundError(
            f"Prepared BANC tables are missing from {data_dir}. "
            "Run BANC_file_converter.ensure_banc_data first."
        )

    # Fallback to legacy names or uncompressed files in downloads
    conn_file = downloads_dir / 'connections_princeton_no_threshold.csv'
    types_file = downloads_dir / 'consolidated_cell_types.csv'
    
    output_neuron_df = data_path / 'flywire_v783_allneurons_neuron_df.csv'
    
    # Check if raw files exist
    # If output files already exist, we don't strictly need the .gz files
    if output_neuron_df.exists() and conn_file.exists():
        return str(output_neuron_df), str(conn_file)

    if not conn_file_gz.exists() or not types_file_gz.exists():
        # Check if uncompressed files exist (maybe user extracted them manually)
        if conn_file.exists() and types_file.exists():
             pass # Proceed to generate neuron df if needed
        else:
            # Generic error message for missing files
            raise FileNotFoundError(
                f"Required data files not found in {data_dir}.\n"
                f"Please ensure the following files exist in {downloads_dir}:\n"
                "1. connections_princeton_no_threshold.csv.gz (or connections_princeton.csv.gz)\n"
                "2. consolidated_cell_types.csv.gz (or neurons.csv.gz)\n"
                "3. sk_lod1_783_healed.zip (optional, for visualization)\n"
                "If using BANC, ensure BANC_file_converter has run successfully."
            )
        
    # Extract if needed
    if not conn_file.exists():
        print(f"Extracting {conn_file_gz}...")
        extract_gz(conn_file_gz, conn_file)
        
    if not types_file.exists():
        print(f"Extracting {types_file_gz}...")
        extract_gz(types_file_gz, types_file)
        
    # Create unified neuron DataFrame if needed
    if not output_neuron_df.exists():
        print("Generating unified neuron DataFrame...")
        
        # Read connections to calculate synapse counts
        print("  Reading connections...")
        # Use string for IDs to handle large integers
        df_conn = pd.read_csv(conn_file, dtype={'pre_root_id': str, 'post_root_id': str})
        
        # Calculate pre counts (outgoing)
        print("  Calculating pre counts...")
        pre_counts = df_conn.groupby('pre_root_id')['syn_count'].sum().reset_index()
        pre_counts.columns = ['bodyId', 'pre']
        
        # Calculate post counts (incoming)
        print("  Calculating post counts...")
        post_counts = df_conn.groupby('post_root_id')['syn_count'].sum().reset_index()
        post_counts.columns = ['bodyId', 'post']
        
        # Read types
        print("  Reading cell types...")
        df_types = pd.read_csv(types_file, dtype={'root_id': str})
        df_types = df_types.rename(columns={'root_id': 'bodyId', 'primary_type': 'type'})
        
        # Merge everything
        print("  Merging data...")
        # Start with all unique bodyIds from types
        df_neuron = df_types[['bodyId', 'type']].copy()
        normalize_flywire_id_columns(df_neuron, ['bodyId'])
        
        # Merge counts
        df_neuron = df_neuron.merge(pre_counts, on='bodyId', how='left')
        df_neuron = df_neuron.merge(post_counts, on='bodyId', how='left')
        
        # Fill NaNs with 0
        df_neuron['pre'] = df_neuron['pre'].fillna(0).astype(int)
        df_neuron['post'] = df_neuron['post'].fillna(0).astype(int)
        
        # Save
        print(f"  Saving to {output_neuron_df}...")
        df_neuron.to_csv(output_neuron_df, index=False)
        print("Done.")
        
    return str(output_neuron_df), str(conn_file)


def prepare_fafb_data(data_dir):
    """Backward-compatible alias for :func:`prepare_flywire_data`."""

    return prepare_flywire_data(data_dir)

def get_fafb_skeleton_zip(data_dir):
    """Get path to skeleton zip file."""
    data_path = Path(data_dir)

    if is_banc_dataset(data_path.name):
        return None
    
    # 1. Check for standardized name (from FAFB_file_converter)
    # Try to guess dataset name from dir name or standard
    dataset_name = data_path.name
    std_zip = data_path / f"{dataset_name}_skeletons.zip"
    if std_zip.exists():
        return str(std_zip)
        
    # 2. Check for original name in root
    zip_path = data_path / 'sk_lod1_783_healed.zip'
    if zip_path.exists():
        return str(zip_path)
        
    # 3. Check in downloads
    downloads_zip = data_path / 'downloads' / 'sk_lod1_783_healed.zip'
    if downloads_zip.exists():
        return str(downloads_zip)
        
    print(f"Warning: Skeleton zip not found in {data_dir} or downloads")
    return None

def get_fafb_skeleton_parquet(data_dir):
    """Get path to skeleton parquet file."""
    data_path = Path(data_dir)
    dataset_name = data_path.name
    std_pq = data_path / f"{dataset_name}_skeletons.parquet"
    if std_pq.exists():
        return str(std_pq)
    return None


# =============================================================================
# FAFB skeleton quality pipeline (shared with the visualization pipeline)
# =============================================================================
# The visualization pipeline checks FAFB skeletons in this order:
#   1. local first  - extrusion-fixed skeletons cached under
#                     ``cache/{dataset}/API_cache/skeletons/``, then the
#                     healed skeleton bundle (``{bodyId}.swc``),
#   2. extrusion test - edge-length analysis on the local skeletons, with
#                     per-neuron results cached in
#                     ``cache/{dataset}/extrusion_check_results.parquet``,
#   3. online fallback - extrusion-affected or missing neurons are fetched
#                     through the CAVE API (token-gated).
# These helpers expose that pipeline so every consumer (e.g. NBLAST
# dotprops building) follows the same behavior.

EXTRUSION_CHECK_FILENAME = "extrusion_check_results.parquet"


def extrusion_check_cache_path(project_root, dataset_folder):
    """Path of the cached extrusion check results for a dataset folder."""
    return Path(project_root) / "cache" / dataset_folder / EXTRUSION_CHECK_FILENAME


def load_extrusion_check_cache(project_root, dataset_folder):
    """Cached extrusion results: {bodyId(str): has_extrusion(bool)}."""
    path = extrusion_check_cache_path(project_root, dataset_folder)
    if not path.exists():
        return {}
    try:
        import pandas as pd

        df = pd.read_parquet(path)
        return dict(zip(df["bodyId"].astype(str), df["has_extrusion"]))
    except Exception:
        return {}


def save_extrusion_check_cache(project_root, dataset_folder, results):
    """Persist new extrusion check results (best-effort)."""
    if not results:
        return
    try:
        import pandas as pd

        path = extrusion_check_cache_path(project_root, dataset_folder)
        path.parent.mkdir(parents=True, exist_ok=True)
        df = pd.DataFrame({
            "bodyId": [str(b) for b in results.keys()],
            "has_extrusion": [bool(v) for v in results.values()],
        })
        df.to_parquet(path, index=False)
    except Exception:
        pass


def detect_extrusion(neuron, simplification=0.95, tube_points=6):
    """Whether a skeleton carries extrusion artifacts (edge-length analysis).

    Mirrors ``VisualizeSkeleton._detect_extrusions_in_skeletons``: convert
    the skeleton to a simplified tube mesh and flag neurons whose edge
    lengths spike (ratio > 10 or a single edge > 50,000 nm).

    The analysis is vectorized over the mesh's unique edges (``trimesh``
    edge index) instead of a Python loop over faces — identical statistics,
    ~20x faster; the open3d quadric decimation (the dominant phase) is
    skipped when the tube mesh is already at or below the target face count.
    """
    import numpy as np
    import navis

    try:
        if hasattr(neuron, "nodes") and "radius" in neuron.nodes.columns:
            invalid = (neuron.nodes["radius"] <= 0) | neuron.nodes["radius"].isna()
            if invalid.any():
                neuron.nodes.loc[invalid, "radius"] = 1
        elif hasattr(neuron, "nodes"):
            neuron.nodes["radius"] = 1

        mesh_neuron = navis.conversion.tree2meshneuron(
            neuron, tube_points=tube_points, use_normals=True
        )
        if not hasattr(mesh_neuron, "trimesh"):
            return False

        n_faces = len(mesh_neuron.trimesh.faces)
        target_faces = max(100, int(n_faces * (1 - simplification)))
        if n_faces > target_faces:
            # Use the same accelerated fine-quality decimator as FAFB
            # visualization/cache preparation.  It prefilters very large
            # tube meshes with one cheap clustering pass, then uses QEM for
            # the final target.  Small meshes fall back to direct QEM.
            try:
                from flywire_mesh_cache import simplify_mesh_fine
            except ImportError:
                from .flywire_mesh_cache import simplify_mesh_fine
            mesh = simplify_mesh_fine(mesh_neuron.trimesh, target_faces)
        else:
            # Already small enough: analyzing the tube mesh directly avoids
            # the (dominant) decimation cost without changing the result.
            mesh = mesh_neuron.trimesh

        edge_ends = mesh.vertices[mesh.edges_unique]
        edge_lengths = np.linalg.norm(
            edge_ends[:, 0, :] - edge_ends[:, 1, :], axis=1
        )
        if len(edge_lengths) == 0:
            return False

        median_edge = np.median(edge_lengths)
        max_edge = np.max(edge_lengths)
        edge_ratio = max_edge / median_edge if median_edge > 0 else 0
        return bool(edge_ratio > 10 or max_edge > 50000)
    except Exception:
        return False


def _extrusion_worker(task, simplification=0.95):
    """Module-level worker for the parallel extrusion check (picklable)."""
    body_id, neuron = task
    return body_id, bool(detect_extrusion(neuron, simplification=simplification))


def flag_extrusions(project_root, dataset_folder, skeletons, verbose=False,
                    log=None, simplification=0.95, n_workers=0):
    """Extrusion check with cached results; returns flagged body ids (int).

    ``skeletons`` maps bodyId -> TreeNeuron. Previously checked neurons are
    served from ``extrusion_check_results.parquet``; new results are
    persisted so the analysis runs once per neuron.

    Unchecked neurons are analyzed in a parallel batch (process pool,
    ``n_workers``; 0 = auto up to 8). Platforms/sandboxes where the pool
    cannot start (e.g. no POSIX semaphores) fall back to a serial pass, so
    the check always completes.
    """
    import functools
    import os
    import sys
    from concurrent.futures import ProcessPoolExecutor

    from tqdm import tqdm

    # Skeleton loaders may preserve body IDs as strings (the FAFB neuron
    # tables intentionally use strings to avoid precision loss), while this
    # routine normalizes IDs to ``int`` before looking them up. Normalize the
    # mapping once at the boundary so ``skeletons[body_id]`` remains valid for
    # both ZIP-loaded and API-cached skeletons.
    normalized_skeletons = {
        int(body_id): neuron
        for body_id, neuron in skeletons.items()
    }
    skeletons = normalized_skeletons

    cache = load_extrusion_check_cache(project_root, dataset_folder)
    flagged = [int(b) for b in skeletons if cache.get(str(b), False)]
    to_check = [int(b) for b in skeletons if str(b) not in cache]
    if not to_check:
        if flagged and (log or verbose):
            (log or print)(
                f"Extrusion check: {len(flagged)} known issue(s) from cache."
            )
        return flagged

    def _report(msg):
        if log is not None:
            log(msg)
        elif verbose:
            print(msg)

    new_results = {}
    pbar = tqdm(total=len(to_check), desc="Checking extrusions", unit="neuron",
                disable=not verbose, leave=False, file=sys.stdout)
    worker = functools.partial(_extrusion_worker, simplification=simplification)

    workers = int(n_workers) if int(n_workers) > 0 else min(
        8, len(to_check), os.cpu_count() or 1)
    if workers > 1:
        try:
            import multiprocessing as mp

            # fork inherits the parent's navis/open3d imports (no per-worker
            # startup cost) and is available on macOS/Linux; the serial pass
            # below covers environments where the pool cannot start.
            ctx = (mp.get_context("fork")
                   if hasattr(mp, "get_context")
                   and "fork" in mp.get_all_start_methods()
                   else mp.get_context("spawn"))
            with ProcessPoolExecutor(max_workers=workers, mp_context=ctx) as ex:
                for body_id, has_extrusion in ex.map(
                        worker,
                        [(bid, skeletons[bid]) for bid in to_check],
                        chunksize=max(1, len(to_check) // (workers * 4))):
                    new_results[str(body_id)] = has_extrusion
                    if has_extrusion:
                        flagged.append(body_id)
                    pbar.update(1)
                    pbar.set_postfix_str(f"{body_id}")
        except Exception:
            # The pool could not start (or died mid-run): redo the batch
            # serially so the check always completes.
            new_results = {}
            flagged = [int(b) for b in skeletons if cache.get(str(b), False)]
            pbar.n = 0
            pbar.refresh()
            for bid in to_check:
                has_extrusion = detect_extrusion(
                    skeletons[bid], simplification=simplification
                )
                new_results[str(bid)] = has_extrusion
                if has_extrusion:
                    flagged.append(bid)
                pbar.update(1)
                pbar.set_postfix_str(f"{bid}")
    else:
        for bid in to_check:
            has_extrusion = detect_extrusion(
                skeletons[bid], simplification=simplification
            )
            new_results[str(bid)] = has_extrusion
            if has_extrusion:
                flagged.append(bid)
            pbar.update(1)
            pbar.set_postfix_str(f"{bid}")

    pbar.close()
    save_extrusion_check_cache(project_root, dataset_folder, new_results)
    if flagged:
        _report(f"Extrusion check: {len(flagged)} neuron(s) flagged for "
                "API replacement.")
    return flagged
